import type { INotifyPropertiesChanged } from '../events';
import { type ViewModelFactory, useViewModel } from './use-view-model';

/** Ensures a unique instance per component that is generated by the factory is created and watches the view model for changes. Returns the view model instance.
 * @deprecated In future versions this hook will be removed, switch to {@link useViewModel}.
 * @template TViewModel The type of view model to create.
 * @param viewModelFactory The view model factory callback that initializes the instance.
 * @param watchedProperties Optional, a render will be requested when only one of these properties has changed.
 */
export function useViewModelFactory<TViewModel extends INotifyPropertiesChanged>(viewModelFactory: ViewModelFactory<TViewModel>, watchedProperties?: readonly (keyof TViewModel)[]): TViewModel {
    return useViewModel(viewModelFactory, [], watchedProperties);
}