import type { INotifyPropertiesChanged } from '../viewModels';
import { type DependencyList, type useMemo, useRef } from 'react';
import { useViewModel } from './UseViewModel';

const emptyDeps: DependencyList = [];

/**
 * Represents a view model factory callback.
 * @template TViewModel The type of view model to create.
 */
export type ViewModelFactory<TViewModel extends INotifyPropertiesChanged> = () => TViewModel;

/**
 * Ensures a view models instance per component generated by the factory and watched for changes. Whenever the provided deps
 * change a new instance is created, similar to {@link useMemo}.
 * @template TViewModel The type of view model to create.
 * @param viewModelFactory The view model factory callback for creating an instance.
 * @param deps Dependencies of the callback, whenever these change the callback is called again, similar to {@link useMemo}.
 * @returns Returns the created view model instance.
 */
export function useViewModelMemo<TViewModel extends INotifyPropertiesChanged>(viewModelFactory: ViewModelFactory<TViewModel>, deps: DependencyList): TViewModel {
    const normalizedDeps = deps === null || deps === undefined || !Array.isArray(deps) ? emptyDeps : deps;

    const cachedDependencies = useRef(normalizedDeps);
    const viewModelRef = useRef<TViewModel | null>(null);

    if (viewModelRef.current === null || cachedDependencies.current.length !== normalizedDeps.length || cachedDependencies.current.some((cachedDependency, dependencyIndex) => cachedDependency !== normalizedDeps[dependencyIndex])) {
        cachedDependencies.current = normalizedDeps.slice();
        viewModelRef.current = viewModelFactory();
    }

    const { current: viewModel } = viewModelRef;
    useViewModel(viewModel);

    return viewModel;
}